/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/utils/cn";
import FixedSidebar from "@/components/fixed-sidebar";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(" flex h-full min-h-screen flex-col ", inter.className)}
      >
        <Navbar />

        <div className="flex h-full w-full  ">
          <FixedSidebar />

          <section className="flex w-full flex-col">
            <Header />
            <div className="flex h-full  ">
              <Sidebar />
              <main className=" h-full w-full bg-gray-200/80 p-2 ">
                {children}
              </main>
            </div>
          </section>
        </div>
      </body>
    </html>
  );
}
